#!jinja
CREATE TABLE MFR_SCHEMA.CUSTOMER_WEST (
	CUSTOMER_ID NUMBER(19,0),
	FIRST_NAME VARCHAR(200),
	LAST_NAME VARCHAR(200),
	PHONE_NO VARCHAR(200),
	EMAIL VARCHAR(200),
	STATE VARCHAR(200)
);
GRANT OWNERSHIP ON TABLE MFR_SCHEMA.CUSTOMER_WEST TO ROLE {{owner}};
EXECUTE IMMEDIATE FROM '2_insert_table_customer_test.sql';